### PR TITLE
Updates to Prometheus 2

### PR DESCRIPTION
**Pull request by thomasjpfan**
Updates to Prometheus 2! #1 

Change Log:

1. In Dockerfile, switches to root user to use `chmod`, since prometheus 2 sets the default user to nobody.
2. `-storage.local.path` becomes `--storage.tsdb.path` in prometheus 2 cli.
3. `-alertmanager.url` configuration is move to `prometheus.yml`.
4. Alert rules are expressed in a YAML format.
5. Updates documentation to reflect changes.
6. Update golang to 1.9.2

### CODE REVIEW

**Comment by vfarcic** [comment]
Amazing PR. I'll go through it over the weekend and get back to you if there are any problems.

**Comment by patrickleet** [comment]
According to their docs, 2.0 IS NOT backwards compatible with old prometheus data.

Might consider a different image name? don't want a whole bunch of people updating to latest and everything crashing comes crashing down.

**Comment by patrickleet** [comment]
https://prometheus.io/docs/prometheus/latest/migration/

**Comment by vfarcic** [comment]
We need to:

1. Be clear in release notes and the docs that data needs to be migrated.
2. Make sure that all the DFM options are backwards compatible.

Those who use this project for the first time should have no problem. Those who upgrade should be OK if they read the docs or release notes. What I'm not sure is how many update their software blindly and whether there is anything we can do to prevent those from crashing.

**Comment by thomasjpfan** [comment]
2. Command line flags: `-alertmanager.url`, `-log.format`, `-storage.local.*`, and `-storage.remote.*` were removed in 2.0. Since DFM uses the prefix `ARG` to pass in these flags, users that rely on the removed flags would be out of luck. We could map these flags to their corresponding 2.0 flags, while ignoring flags that can't be mapped. In the case of `-alertmanager.url` we can just use that to configure `prometheus.yml`.

1. Database migration options:

a. Have both 1.8.1 and 2.0 in the image, check the data folder for the database format and run the compatible version. The codebase would have to support both versions and the image would increase in size.
b. Create a separate branch for 2.0 and keep the latest at 1.8.1. To keep feature parity, the branches would have to manually be kept in sync, keeping compatibly in mind.
c. When upgrading from 1.8.1 to 2.0, log an error to stdout, and return a webpage at port 8080 directing the user to go to the docs. The docs will detail all the benefits of migrating.

I would go with option c.

On a side note, it is normally bad practice to use a docker image with the tag `latest` in production. How much should we consider users that do this?

**Comment by vfarcic** [comment]
1. Agreed.
2. I prefer option C as well. It's a good idea but I'm not sure whether we can do that unless `prometheus` binary fails. If that's the case, it should not be a problem.

**Comment by thomasjpfan** [comment]
The folder structure for the database between 1.8.1 and 2.0 are different. Specifically, we can look for a folder called `wal` to indicate that it was a database created by 2.0.

If we are going with option C, I do not think we need to support the old flags. The docs would direct the user on how to migrate to the new 2.0 flags/environmental variables. What do you think?

**Comment by vfarcic** [comment]
I think that it'll be faster and better to make it backward compatible. There are too many references to DFM in too many places (blogs, books, docs, etc.). People would execute one of the instructions and encounter problems due to different env. vars. and labels. I should change all of the references but that'll take a lot of time. The alternative would be to keep the `latest` tag pointing to the image with prom 1.x like what Docker did with their Registry. I'm not fond of that approach. It generated a lot of confusion with the `registry`. Another alternative is to create a fully new image (e.g., `docker-flow-monitor-2`) but that might be confusing as well. All in all, I don't think there's an easy way out. To me, backwards compatibility (when possible) still sounds like the best option.

**Comment by thomasjpfan** [comment]
Okay, I’ll add backwards compatibility.

**Comment by thomasjpfan** [comment]
When running v2 targeting the v1 database, it ignores the v1 data and creates its own database structure. All the old v1 data is still there, but it would not be used. When a user goes back to v1, it would be able to continue off the data it had before, ignoring anything created by v2.

The only time prometheus crashes, is when the database started out as v2 (never initialized a v1 database), and tried to run v1 on it. I don't think this should be an issue.

A user upgrading from v1 to v2 will see the old data missing on the dashboard. I am not sure about what to do with this situation.

**Comment by vfarcic** [comment]
Going from v2 to v1 should not happen. If it does, it's not something we should worry about.

I think that missing data is OK. They will consult the docs and find out that they need to migrate. Prometheus data is not long lasting anyways.

**Comment by thomasjpfan** [comment]
Besides the prometheus 2 support, I refactored some of the configuration generation code and removed a bunch of newlines. Basically, `GetGlobalConfig`, `GetScrapeConfig`, `GetRemoteConfig`, and `GetAlertManagerConfig` returns strings that do not beginning or end with `\n`, thus `WriteConfig` will add the newlines between them it is needed.

With the migration documentation, I believe this PR is complete.

**Comment by vfarcic** [comment]
Amazing PR! Thank you @thomasjpfan.

**Pull request merged**
